version: "3.8"

services:
  zookeeper:
    container_name: "zookeeper"
    image: zookeeper:0.0.1
    ports:
      - "8000:8000"

  postgres:
    container_name: "postgres-zookeeper"
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  broker1:
    image: broker:0.1.1
    container_name: broker1

  broker2:
    image: broker:0.1.1
    container_name: broker2