health_check_path: "/healthz"
port: 8000
brokers:
  - name: "node1"
    host: "http://broker:8080"

postgres:
  host: "postgres-zookeeper"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: "postgres"
