name: Deploy Image to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'

      - name: 'Build Binary'
        run: make build

  push-store-image:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        env:
          IMAGE_NAME: ghcr.io/new-kafka/zookeeper
          TAG: ${{ github.ref }}
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest
          docker push ${{ github.repository }}:${{ github.sha }}
          docker push ${{ github.repository }}:latest

  deploy:
    needs: push-store-image
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to Production'
        if: github.event_name == 'workflow_dispatch'
        uses: appleboy/ansible-action@v2
        with:
          playbook: deploy.yml
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
